### ISSUE TITLE
ensure site renders for mobile and tablet alike

### ISSUE THREAD

**Issue by jakebolam** [tophat/opensource.tophat.com#54]
ensure site renders for mobile and tablet alike.

Here are some examples where its falling down:
![screen shot 2018-12-04 at 5 12 59 pm](https://user-images.githubusercontent.com/3534236/49476465-0b5e4180-f7e8-11e8-8943-207ec1294b9a.png)
![screen shot 2018-12-04 at 5 13 11 pm](https://user-images.githubusercontent.com/3534236/49476466-0b5e4180-f7e8-11e8-8317-8975845e7a1f.png)

**Comment by AnvarGazizovTH** [comment]
The markup that was not rendering properly on mobile is no longer on the page and the rest of the page is responsive.
