### ISSUE TITLE
Revamp the website

### ISSUE THREAD

**Issue by mcataford** [tophat/opensource.tophat.com#64]
It would be nice to not have to manually add projects to the website and reduce the amount of copy/pasting going on in the webpage's source.

Any ideas welcome!

**Comment by noahnu** [comment]
Definitely json over csv (easier to manipulate in JS)

**Comment by mcataford** [comment]
I agree -- A long time ago, a suggestion was made to leverage the Jekyll integration that GH has to generate the site so that you could use templating without a whole lot of effort.

I do agree that json >>>> CSV.
